const certificates = [
  {
    title: 'TOEFL Preparation Specialization',
    institution: 'University of California, Irvine',
    description: 'TOEFL skills and test strategy.',
    skills: ['TOEFL reading', 'TOEFL writing', 'TOEFL speaking', 'TOEFL listening'],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93',
    image: '/certificates/toefl-preparation.jpeg',
    date: 'February 11, 2022',
  },
  {
    title: 'Machine Learning Specialization',
    institution: 'Stanford University & DeepLearning.AI',
    description:
      'Core ML: supervised learning, advanced models, then unsupervised work, recommenders, and reinforcement learning.',
    skills: [
      'Scikit Learn',
      'Supervised Learning',
      'Classification And Regression Tree (CART)',
      'NumPy',
      'Unsupervised Learning',
      'Decision Tree Learning',
      'Reinforcement Learning',
      'Deep Learning',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/machine-learning.jpeg',
    date: 'August 31, 2024',
  },
  {
    title: 'Generative AI and LLMs: Architecture and Data Preparation',
    institution: 'IBM',
    description:
      'How generative models and LLMs are structured and how to prepare text data for NLP.',
    skills: [
      'PyTorch',
      'Jupyter',
      'Generative AI',
      'Natural Language Processing',
      'Data Processing',
      'Text Mining',
      'Large Language Modeling',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/generative-ai-llms.jpeg',
    date: 'February 14, 2025',
  },
  {
    title: 'Algorithmic Toolbox',
    institution: 'University of California San Diego',
    description: 'Classic algorithmic patterns and writing efficient, reliable solutions.',
    skills: [
      'Computational Thinking',
      'Algorithms',
      'Development Testing',
      'Computer Programming',
      'Software Testing',
      'Programming Principles',
      'Program Development',
      'Test Engineering',
      'Theoretical Computer Science',
      'Design Strategies',
      'Bioinformatics',
      'Test Case',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/algorithmic-toolbox.jpeg',
    date: 'March 17, 2025',
  },
  {
    title: 'Neural Networks and Deep Learning',
    institution: 'DeepLearning.AI',
    description: 'Building and training neural networks from the ground up.',
    skills: [
      'Artificial Neural Networks',
      'Deep Learning',
      'Performance Tuning',
      'Supervised Learning',
      'Machine Learning',
      'Calculus',
      'Linear Algebra',
      'Artificial Intelligence',
      'Python Programming',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/neural-networks-deep-learning.jpeg',
    date: 'September 22, 2024',
  },
  {
    title: 'Gen AI Foundational Models for NLP & Language Understanding',
    institution: 'IBM',
    description:
      'Text as model inputs, word embeddings, neural language models, and sequence-to-sequence setups.',
    skills: [
      'PyTorch (Machine Learning Library)',
      'Deep Learning',
      'Artificial Neural Networks',
      'Generative AI',
      'Natural Language Processing',
      'Machine Learning Methods',
      'Feature Engineering',
      'Text Mining',
      'Large Language Modeling',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/gen-ai-foundational-models.jpeg',
    date: 'March 16, 2025',
  },
  {
    title: 'Version Control',
    institution: 'Meta',
    description: 'Version control on the command line and day-to-day repo workflows.',
    skills: [
      'Command-Line Interface',
      'Github',
      'Software Development',
      'Unix Commands',
      'Version Control',
      'Linux',
      'Git (Version Control System)',
      'File Management',
      'Web Development',
      'Software Versioning',
      'Software Development Tools',
      'Linux Commands',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/version-control.jpeg',
    date: 'August 31, 2023',
  },
  {
    title: 'Java Programming: Solving Problems with Software',
    institution: 'Duke University',
    description: 'Java, object-oriented code, and end-to-end small program design.',
    skills: [
      'Algorithms',
      'Data Analysis',
      'Java',
      'Software Testing',
      'Computer Programming',
      'Software Design',
      'Object Oriented Programming (OOP)',
      'Data Processing',
      'Integrated Development Environments',
      'Debugging',
      'Problem Solving',
      'Statistical Analysis',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/java-programming.jpeg',
    date: 'March 28, 2023',
  },
  {
    title: 'Django Web Framework',
    institution: 'Meta',
    description: 'Backend apps with solid data modeling and common security practices.',
    skills: [
      'Web Servers',
      'Django (Web Framework)',
      'Database Management',
      'Application Frameworks',
      'Data Modeling',
      'Back-End Web Development',
      'Application Security',
      'Hypertext Markup Language (HTML)',
      'MySQL',
      'Web Development',
      'Web Applications',
      'Database Development',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/django-web-framework.jpeg',
    date: 'September 22, 2023',
  },
  {
    title: 'Programming in Python',
    institution: 'Meta',
    description:
      'Python syntax, objects and classes, testing, debugging, and core data structures.',
    skills: [
      'Development Environment',
      'Django (Web Framework)',
      'Software Testing',
      'Computer Programming',
      'Object Oriented Programming (OOP)',
      'Unit Testing',
      'Integrated Development Environments',
      'Debugging',
      'Programming Principles',
      'Data Structures',
      'Test Driven Development (TDD)',
      'Python Programming',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/programming-in-python.jpeg',
    date: 'August 27, 2023',
  },
  {
    title: 'Introduction to Back-End Development',
    institution: 'Meta',
    description:
      'How front-end, back-end, and full-stack roles differ; building styled pages and how servers fit in.',
    skills: [
      'Web Servers',
      'User Interface (UI)',
      'Hypertext Markup Language (HTML)',
      'General Networking',
      'Bootstrap (Front-End Framework)',
      'Full-Stack Web Development',
      'React.js',
      'Back-End Web Development',
      'Cascading Style Sheets (CSS)',
      'Front-End Web Development',
      'JavaScript Frameworks',
      'Responsive Web Design',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/introduction-to-backend.jpeg',
    date: 'April 24, 2023',
  },
  {
    title: 'Introduction to Databases for Back-End Development',
    institution: 'Meta',
    description:
      'Designing small databases, writing queries, and when relational vs. non-relational stores make sense.',
    skills: [
      'Database Design',
      'Databases',
      'Query Languages',
      'MySQL',
      'Database Management Systems',
      'Relational Databases',
      'NoSQL',
      'SQL',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/introduction-to-databases.jpeg',
    date: 'September 1, 2023',
  },
  {
    title: 'Learning How to Learn: Powerful mental tools to help you master tough subjects',
    institution: 'Deep Teaching Solutions',
    description: 'How to study deeply, manage time, and stick with hard material.',
    skills: [
      'Learning Strategies',
      'Productivity',
      'Willingness To Learn',
      'Time Management',
      'Human Learning',
      'Mental Concentration',
      'Problem Solving',
      'Cognitive flexibility',
      'Creativity',
      'Stress Management',
      'Self-Discipline',
      'Growth Mindedness',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/learning-how-to-learn.jpeg',
    date: 'March 25, 2023',
  },
  {
    title: 'APIs',
    institution: 'Meta',
    description:
      'REST-style API design, validation, auth concerns, and shipping static docs clients can use.',
    skills: [
      'Django',
      'XML',
      'API Design',
      'Performance Tuning',
      'Data Validation',
      'Authorizatio',
      'Restful API',
      'JSON',
      'Debugging',
      'Application Programming Interface (API)',
      'Software Documentation',
      'Test Tools',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93', // URL from the first certificate
    image: '/certificates/apis.jpeg',
    date: 'October 14, 2023',
  },
  {
    title: 'Foundations: Data, Data, Everywhere',
    institution: 'Google',
    description:
      'Data ecosystems, analytical thinking, spreadsheets and queries, visualization, and ethics.',
    skills: [
      'Data Cleansing',
      'Spreadsheet Software',
      'Data Management',
      'Data Analysis',
      'Data Ethics',
      'Data Processing',
      'Data-Driven Decision-Making',
      'Data Visualization',
      'Google Sheets',
      'Analytical Skills',
      'Data Sharing',
      'Data Visualization Software',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93',
    image: '/certificates/data-analysis-foundations.jpeg', // Assuming a relevant image name
    date: 'February 1, 2022',
  },
  {
    title: 'Technical Support Fundamentals',
    institution: 'Google',
    description:
      'OS basics, networking, installs, hardware context, and clear customer-facing support.',
    skills: [
      'Information Technology',
      'Operating Systems',
      'Technical Communication',
      'Computer Networking',
      'Software Installation',
      'Customer Support',
      'Technical Support',
      'End User Training and Support',
      'Computer Architecture',
      'Microsoft Windows',
      'Computer Hardware',
      'Linux',
    ],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93',
    image: '/certificates/technical-support-fundamentals.jpeg', // Assuming a relevant image name
    date: 'February 1, 2022',
  },
  {
    title: 'Introduction to Artificial Intelligence (AI)',
    institution: 'IBM',
    description:
      'ML and deep learning at a high level plus where generative AI fits and basic responsible-use framing.',
    skills: ['Natural Language Processing', 'Generative AI', 'ChatGPT'],
    courseraUrl: 'https://coursera.org/share/63440a205d4aabb6773832044c5d0d93',
    image: '/certificates/introduction-to-artificial-intelligence.jpeg',
    date: 'February 26, 2023',
  },
  {
    title: 'Python Essentials for MLOps',
    institution: 'Duke University',
    description:
      'Automated tests, small CLIs, and HTTP surfaces to support repeatable ML workflows.',
    skills: [
      'Command-Line Interface',
      'Software Testing',
      'Test Automation',
      'Data Manipulation',
      'NumPy',
      'Machine Learning',
      'Data Import/Export',
      'Program Development',
      'Scripting',
      'MLOps',
      'Pandas',
    ],
    courseraUrl: 'https://coursera.org/share/e0df2ef182ae3dd90470d2b45359cbdf',
    image: '/certificates/python-essentials-mlops.png',
    date: 'Jul 3, 2025',
  },
];

export default certificates;
